import Image from "next/image";
import Head from "next/head";
import styles from "./Developers.module.css";
import Navigation from "../Layout/Navigation";
import GabrielImg from "../../public/assets/images/gabriel.webp";
import NicolasImg from "../../public/assets/images/Profile.webp";
import TeamsLogo from "../../public/assets/images/team.webp";

const Developers = () => {
  return (
    <>
      <Head>
        <title>JS TEAM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <main className="w-[100vw] h-[100vh] p-5 flex flex-col justify-center items-center">
        <h2 className="text-primary-text mt-[100px] text-5xl sm:mt-0  sm:text-7xl font-semibold mb-10 ">
          Developer
        </h2>

        <div className="w-[20rem] max-w-sm bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700 overflow-hidden">
          <div className="h-[20rem] w-full relative">
            <Image
              src={NicolasImg}
              alt="Nicolas Profile"
              layout="fill"
              objectFit="cover"
              objectPosition="center"
            />
          </div>
          <div className="flex flex-col items-center pb-10">
            <h5 className="mb-1 text-xl font-medium text-gray-900 dark:text-white">
              Nicolas Peña
            </h5>
            <span className="text-sm text-gray-500 dark:text-gray-400">
              Fullstack Developer
            </span>
            <div class="flex mt-4 space-x-3 md:mt-6">
              <a
                target="_blank"
                href="https://github.com/Nicolasp-dev"
                class="inline-flex items-center py-2 px-4 text-sm font-medium text-center text-white bg-primary-text rounded-lg hover:bg-mid-green focus:ring-4 focus:outline-none focus:bg-mid-green dark:bg-mid-green dark:hover:bg-mid-green dark:focus:ring-bg-mid-green"
              >
                Git-Hub
              </a>
              <a
                target="_blank"
                href="https://www.linkedin.com/in/nicolaspe%C3%B1a-dev/"
                class="inline-flex items-center py-2 px-4 text-sm font-medium text-center text-gray-900 bg-white rounded-lg border border-gray-300 hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-700 dark:focus:ring-gray-700"
              >
                LinkedIn
              </a>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Developers;
